version: "3.8"

services:
  easytier-core:
    image: ghcr.io/229033891/et:dev-en
    container_name: easytier-core
    hostname: FNNAS
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /vol1/1000/docker/easytier/config:/config
    command:
      - --daemon
      - --config-dir
      - /config
      - --config-server
      - udp://et.scmec.vip:22020/admin
      - --secure-mode
