//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod devices;
pub mod groups;
pub mod groups_permissions;
pub mod managed_config_revisions;
pub mod networks;
pub mod peer_conn_history;
pub mod permissions;
pub mod tower_sessions;
pub mod user_config_tokens;
pub mod user_running_network_configs;
pub mod users;
pub mod users_groups;
