//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 单次采样：某设备上某个网络实例到某个对端 peer 的连接汇总。
///
/// - `latency_us` / `loss_rate` 取该 peer 所有连接里的最优值（延迟取最小、丢包取最小）
/// - `rx_bytes` / `tx_bytes` 是该 peer 所有连接的累计计数器之和（**不是速率**），
///   速率由查询侧对相邻采样做差分得到，这样连接重置时也不会把数据写脏
/// - `sampled_at` 是 unix 秒
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "peer_conn_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i32,
    #[sea_orm(column_type = "Text")]
    pub machine_id: String,
    #[sea_orm(column_type = "Text")]
    pub instance_id: String,
    pub peer_id: i64,
    #[sea_orm(column_type = "Text")]
    pub peer_hostname: String,
    /// 隧道对端地址 IP:端口（优先 resolved_remote_addr，退化到 remote_addr）
    #[sea_orm(column_type = "Text")]
    pub remote_addr: String,
    #[sea_orm(column_type = "Text")]
    pub tunnel_type: String,
    pub latency_us: i64,
    pub loss_rate: f64,
    pub rx_bytes: i64,
    pub tx_bytes: i64,
    pub conn_count: i32,
    pub sampled_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
